# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          random=$RANDOM
          STRING=$(tr -dc A-Za-z </dev/urandom | head -c 13 ; echo '')
          curl https://raw.githubusercontent.com/hc-use-cases/tfe-ci-templates/main/resource.tf -o resource_${random}.tf
          sed -i "s/1/${random}/g" resource_${random}.tf
          sed -i "s/alpha/${STRING}/g" resource_${random}.tf
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: CI
          author_email: call-to-action@example.com
          message: 'Your commit message'
          add: '*.tf'
